# H2 Veritaban? Yap?land?rmas?
spring.datasource.url=jdbc:h2:mem:testdb  # Bellek içi H2 veritaban? URL'si
spring.datasource.driver-class-name=org.h2.Driver  # H2 veritaban? sürücüsünün s?n?f ad?
spring.datasource.username=sa  # Veritaban? kullan?c? ad? (varsay?lan: sa)
spring.datasource.password=  # Veritaban? ?ifresi (varsay?lan: bo?)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect  # Hibernate için H2 veritaban? platformu ayar?

# H2 Konsolunu Aktif Et
spring.h2.console.enabled=true  # H2 konsolunu aktif eder
spring.h2.console.path=/h2-console  # H2 konsolunun eri?im yolu
